# Generated by Django 4.2.20 on 2025-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post_date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('paragraph', models.TextField(max_length=2000)),
            ],
        ),
    ]
